name: "pre-commit autoupdate"
description: "Runs pre-commit autoupdate and opens a PR if necessary"
inputs:
  token:
    description: "A github token with write access to the repository"
    required: true
runs:
  using: "composite"
  steps:
      - uses: actions/checkout@v4
      - name: Setup git
        run: |
          git config --global user.name "Pre-commit automation"
          git config --global user.email "releng+pre-commit-autoupdate@mozilla.com"
        shell: bash
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - run: python -m pip install pre-commit==4.2.0
        shell: bash
      - name: Get commit message
        run: |
          echo "COMMIT_MSG=$(cat .pre-commit-config.yaml | yq -r '.ci.autoupdate_commit_msg // "Update pre-commit config"')" >> $GITHUB_ENV
        shell: bash
      - name: Update files
        run: |
          git checkout -B pre-commit-update
          pre-commit autoupdate -j4
          git add .pre-commit-config.yaml
          git commit -m "${COMMIT_MSG}"
          git push -f origin pre-commit-update
        shell: bash
      - name: Create PR if necessary
        run: |
          curl -sL \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ inputs.token }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos${{ github.reository_owner }}/${{ github.repository }}/pulls \
          -d "{\"title\":\"${COMMIT_MSG}\",\"body\":\"\",\"head\":\"pre-commit-update\",\"base\":\"${{ github.event.repository.default_branch }}\"}"
        shell: bash
